### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [PaulWoitaschek/Voice#1795]
ref: https://monitor.f-droid.org/builds/log/de.ph1b.audiobook/3603012#site-footer

Reading https://github.com/PaulWoitaschek/Voice/commit/8c5cbb585c370f7638aa4f2ed3251efc12a308d0 it means that it NEEDs Java 19?

F-Droid uses Debian Bullseye so it can use Java 11 and 17.

/LE: trying 17 https://gitlab.com/fdroid/fdroiddata/-/commit/0fca5bb4f4b3d2adac519ef719dec4d134563aab

**Comment by PaulWoitaschek** [comment]
Are you affiliated to fdroid? Yes, it needs java 17, like all future projects on AGP 8.

**Comment by licaon-kter** [comment]
Yup, Java17 builds it fine locally, thanks

**Comment by licaon-kter** [comment]
non-FOSS Google libs are brought by the new review thing: https://github.com/PaulWoitaschek/Voice/commit/1ef95f6980091ac8132c43d1f9967c30e79739f9

ref: https://gitlab.com/fdroid/fdroiddata/-/jobs/4494181504#L1103

**Comment by PaulWoitaschek** [comment]
Thanks @licaon-kter !

Would this work?

https://github.com/PaulWoitaschek/Voice/pull/1998

You'd just build with an additional foss property. I.e `./gradlew :app:assembleRelease -Pfoss`

**Comment by licaon-kter** [comment]
```
  - versionName: 8.1.0
    versionCode: 3603027
    commit: 6ab4c1a6c36ef7953d1f967ec31a27c2dff1991d
...
    scandelete:
      - plugins/build
    gradleprops:
      - foss
```

.... builds fine :tada:
